### ISSUE TITLE
libpy_nvblox.so: undefined symbol: _ZNK6nvblox6Mapper13saveLayerCakeERKSs

### ISSUE THREAD

**Issue by balasubramani0395** [NVlabs/nvblox_torch#10]
Hi, 
I have built this project successfully. But I face this issue

`Traceback (most recent call last):
  File "/home/leon/pkgs/nvblox_torch/examples/get_sdf.py", line 74, in <module>
    test_py_dummy_map()
  File "/home/leon/pkgs/nvblox_torch/examples/get_sdf.py", line 49, in test_py_dummy_map
    scene = create_dummy_map()
  File "/home/leon/pkgs/nvblox_torch/examples/get_sdf.py", line 37, in create_dummy_map
    scene = Scene()
  File "/home/leon/pkgs/nvblox_torch/src/nvblox_torch/scene.py", line 25, in __init__
    SceneCls = get_nvblox_scene_class()
  File "/home/leon/pkgs/nvblox_torch/src/nvblox_torch/scene.py", line 17, in get_nvblox_scene_class
    torch.classes.load_library(join_path(get_binary_path(), "libpy_nvblox.so"))
  File "/home/leon/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/home/leon/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/home/leon/.local/share/ov/pkg/isaac_sim-2023.1.1/kit/python/lib/python3.10/ctypes/__init__.py", line 377, in __init__
    self._handle = _dlopen(final_name, mode)
OSError: /home/leon/pkgs/nvblox_torch/src/nvblox_torch/bin/libpy_nvblox.so: undefined symbol: _ZNK6nvblox6Mapper13saveLayerCakeERKSs
There was an error running python`

I saw your comment on another issue to use docker. I have installed curobo, nvblox, nvblox_torch successfully with isaac_sim omni_python. Can I modify the python to omni_python in dockerfile and use local isaac_sim installation to build and run with the docker you suggested?

Is there any other way to fix this issue?

Thanks

**Comment by WhozMe** [comment]
Hi, same problem, I have built the project successfully, but keep facing the same issue when launching with Isaac Sim.

`Traceback (most recent call last):
  File "/home/USER/Desktop/Omniverse/curobo/examples/isaac_sim/collision_checker.py", line 205, in <module>
    main()
  File "/home/USER/Desktop/Omniverse/curobo/examples/isaac_sim/collision_checker.py", line 138, in main
    config = RobotWorldConfig.load_from_config(
  File "/home/USER/Desktop/Omniverse/curobo/src/curobo/wrap/model/robot_world.py", line 105, in load_from_config
    world_collision_checker = create_collision_checker(world_cfg)
  File "/home/USER/Desktop/Omniverse/curobo/src/curobo/geom/sdf/utils.py", line 27, in create_collision_checker
    return WorldBloxCollision(config)
  File "/home/USER/Desktop/Omniverse/curobo/src/curobo/geom/sdf/world_blox.py", line 56, in __init__
    super().__init__(config)
  File "/home/USER/Desktop/Omniverse/curobo/src/curobo/geom/sdf/world_voxel.py", line 36, in __init__
    super().__init__(config)
  File "/home/USER/Desktop/Omniverse/curobo/src/curobo/geom/sdf/world_mesh.py", line 62, in __init__
    super().__init__(config)
  File "/home/USER/Desktop/Omniverse/curobo/src/curobo/geom/sdf/world.py", line 517, in __init__
    self.load_collision_model(self.world_model)
  File "/home/USER/Desktop/Omniverse/curobo/src/curobo/geom/sdf/world_blox.py", line 76, in load_collision_model
    self._blox_mapper = Mapper(
  File "/home/USER/Desktop/Omniverse/pkgs/nvblox_torch/src/nvblox_torch/mapper.py", line 45, in __init__
    self._c_mapper = get_nvblox_mapper_class()(
  File "/home/USER/Desktop/Omniverse/pkgs/nvblox_torch/src/nvblox_torch/mapper.py", line 25, in get_nvblox_mapper_class
    torch.classes.load_library(join_path(get_binary_path(), "libpy_nvblox.so"))
  File "/home/USER/Desktop/Omniverse/Lib/isaac_sim-2023.1.0-hotfix.1/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/home/USER/Desktop/Omniverse/Lib/isaac_sim-2023.1.0-hotfix.1/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/home/USER/Desktop/Omniverse/Lib/isaac_sim-2023.1.0-hotfix.1/kit/python/lib/python3.10/ctypes/__init__.py", line 377, in __init__
    self._handle = _dlopen(final_name, mode)
OSError: /home/USER/Desktop/Omniverse/pkgs/nvblox_torch/src/nvblox_torch/bin/libpy_nvblox.so: cannot open shared object file: No such file or directory
`

**Comment by 15210579725** [comment]
I also face the same problem :OSError: /home/user/pkgs/nvblox_torch/src/nvblox_torch/bin/libpy_nvblox.so: undefined symbol: _ZN3c104impl3cow11cow_deleterEPv

but my undefined symbol is different from @balasubramani0395 
and i have no idea what to do , hope someone could give a help

**Comment by aCodeDog** [comment]
same problem.. :/pkgs/nvblox_torch/src/nvblox_torch/bin/libpy_nvblox.so: undefined symbol: _ZNK6nvblox6Mapper13saveLayerCakeERKSs

**Comment by 15210579725** [comment]
use a new conda enviroment WHOSE torch version could match this demand

**Comment by hjlllll** [comment]
> use a new conda enviroment WHOSE torch version could match this demand

hi, which version of torch can solve this problem? thanks!!!

**Comment by 15210579725** [comment]
I can't quite remember. You could try checking the PyTorch version in the official omni_python, or a version of Torch that matches your computer's CUDA. Remember to reinstall nvblox after creating a new environment.
omni_python pip show torch

**Comment by BIT-DYN** [comment]
@balasubramani0395 

Hi, I'm experiencing the same error.
Have you solved the problem now?

**Comment by RayOwwen** [comment]
I encountered the same problem and resolved it by running the following command:
```
export LD_LIBRARY_PATH=/usr/local/lib
```
![2024-12-24_10-18](https://github.com/user-attachments/assets/bd5d6d1d-669f-4e4c-b527-8b6641457fc3)

**Comment by xibeisiber** [comment]
I set LD_LIBRARY_PATH but it still doesn't work

![Image](https://github.com/user-attachments/assets/df43a003-7da3-491f-955a-e18a566d57de)

**Comment by threedee003** [comment]
I am also getting the same type of error when I am trying to test the `run_mapper.py` example using **sun3d** dataset. I am using Ubuntu 20.04.

`OSError: /home/<user>/nvblox_torch/src/nvblox_torch/bin/libpy_nvblox.so: undefined symbol: _ZNK6nvblox6Mapper13saveLayerCakeERKSs`

Has anyone solved it ?
