### ISSUE TITLE
example code problem

### ISSUE THREAD

**Issue by Sepirence** [NVlabs/nvblox_torch#4]
How are you using nvblox_torch (docker/native/conda/?): 
> Starts from docker [isaac-sim:2023.1.0](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/isaac-sim)
> python 3.10.13
> torch 2.0.1+cu118
> cuda 11.7
> gpu 3090ti
> ubuntu 20.04

Issue Details:

My previous issue was [here](https://github.com/NVlabs/curobo/issues/39#issuecomment-1884370391).

To make it sure, I made new container and reinstalled nvblox-torch in latest version you patched.

Still, make an error before comfronting error on previous issue.

error:
```
[11.314s] app ready
2024-01-12 01:33:35 [12,163ms] [Warning] [omni.kit.hotkeys.core.registry] [Hotkey] duplicated action as SPACE (On Press) with omni.kit.widget.toolbar.omni.kit.widget.toolbar::toolbar::play!
2024-01-12 01:33:35 [12,164ms] [Warning] [omni.kit.hotkeys.core.registry] [Hotkey] Cannot register Global [omni.kit.widget.toolbar] omni.kit.widget.toolbar::toolbar::play.SPACE, error code: Duplicated action definition
[12.551s] RTX ready
[13.204s] Simulation App Startup Complete
2024-01-12 01:33:38 [15,112ms] [Warning] [omni.client.plugin]  Tick: provider_nucleus: Auth: Failed to create transport: Transport constructor is not found by description
2024-01-12 01:33:38 [15,112ms] [Warning] [omni.isaac.core.utils.nucleus] /persistent/app/omniverse/mountedDrives setting not found
Traceback (most recent call last):
  File "/isaac-sim/curobo/examples/isaac_sim/mpc_nvblox_example.py", line 348, in <module>
    main()
  File "/isaac-sim/curobo/examples/isaac_sim/mpc_nvblox_example.py", line 187, in main
    mpc_config = MpcSolverConfig.load_from_robot_config(
  File "/isaac-sim/curobo/src/curobo/wrap/reacher/mpc.py", line 118, in load_from_robot_config
    world_coll_checker = create_collision_checker(world_cfg)
  File "/isaac-sim/curobo/src/curobo/geom/sdf/utils.py", line 27, in create_collision_checker
    return WorldBloxCollision(config)
  File "/isaac-sim/curobo/src/curobo/geom/sdf/world_blox.py", line 56, in __init__
    super().__init__(config)
  File "/isaac-sim/curobo/src/curobo/geom/sdf/world_mesh.py", line 62, in __init__
    super().__init__(config)
  File "/isaac-sim/curobo/src/curobo/geom/sdf/world.py", line 361, in __init__
    self.load_collision_model(self.world_model)
  File "/isaac-sim/curobo/src/curobo/geom/sdf/world_blox.py", line 76, in load_collision_model
    self._blox_mapper = Mapper(
  File "/isaac-sim/nvblox/nvblox_torch/src/nvblox_torch/mapper.py", line 46, in __init__
    self._c_mapper = get_nvblox_mapper_class()(
  File "/isaac-sim/nvblox/nvblox_torch/src/nvblox_torch/mapper.py", line 26, in get_nvblox_mapper_class
    torch.classes.load_library(join_path(cpp_build_path, "libpy_nvblox.so"))
  File "/isaac-sim/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/isaac-sim/extscache/omni.pip.torch-2_0_1-2.0.2+105.1.lx64/torch-2-0-1/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/isaac-sim/kit/python/lib/python3.10/ctypes/__init__.py", line 377, in __init__
    self._handle = _dlopen(final_name, mode)
OSError: /isaac-sim/nvblox/nvblox_torch/src/nvblox_torch/cpp/build/libpy_nvblox.so: cannot open shared object file: No such file or directory
2024-01-12 01:33:40 [17,715ms] [Warning] [omni.core.ITypeFactory] Module /isaac-sim/kit/exts/omni.graph.action/bin/libomni.graph.action.plugin.so remained loaded after unload request.
2024-01-12 01:33:40 [17,719ms] [Warning] [carb] [Plugin: omni.spectree.delegate.plugin] Module /isaac-sim/kit/exts/omni.usd_resolver/bin/libomni.spectree.delegate.plugin.so remained loaded after unload request
2024-01-12 01:33:40 [17,723ms] [Warning] [omni.stageupdate.plugin] Deprecated: direct use of IStageUpdate callbacks is deprecated. Use IStageUpdate::getStageUpdate instead.
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,724ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,725ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-01-12 01:33:40 [17,729ms] [Warning] [carb.audio.context] 1 contexts were leaked
2024-01-12 01:33:41 [17,843ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
2024-01-12 01:33:41 [17,859ms] [Warning] [omni.core.ITypeFactory] Module /isaac-sim/kit/exts/omni.activity.core/bin/libomni.activity.core.plugin.so remained loaded after unload request.
```

Is there any recommendation about CUDA version? I am using 11.7 now and Isaac-sim is stable with your curobo examples that do not use nvblox, but maybe I will update at least version 11.8 or upper.

**Comment by balakumar-s** [comment]
After cloning the latest version of nvblox_torch, did you run compilation step before doing pip install?

```
    sh install_isaac_sim.sh $($omni_python -c 'import torch.utils; print(torch.utils.cmake_prefix_path)')
    pip install .
```

**Comment by Sepirence** [comment]
Yep, it works well. Thank you for helping me.
