### ISSUE TITLE
libpy_nvblox.so: undefined symbol: _ZNK6nvblox6Mapper13saveLayerCakeERKSs

### ISSUE THREAD

**Issue by zhanghua7099** [NVlabs/nvblox_torch#8]
Hi! I build this project sucessfully but can not run the demo. The following error occurs:

```
Traceback (most recent call last):
  File "run_mapper.py", line 67, in <module>
    mapper = Mapper([args.voxel_size, args.voxel_size], ["tsdf", "occupancy"])
  File "/home/usr/PyProject/nvblox_torch/src/nvblox_torch/mapper.py", line 45, in __init__
    self._c_mapper = get_nvblox_mapper_class()(
  File "/home/usr/PyProject/nvblox_torch/src/nvblox_torch/mapper.py", line 25, in get_nvblox_mapper_class
    torch.classes.load_library(join_path(get_binary_path(), "libpy_nvblox.so"))
  File "/home/usr/.local/lib/python3.8/site-packages/torch/_classes.py", line 51, in load_library
    torch.ops.load_library(path)
  File "/home/usr/.local/lib/python3.8/site-packages/torch/_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/usr/PyProject/nvblox_torch/src/nvblox_torch/bin/libpy_nvblox.so: undefined symbol: _ZNK6nvblox6Mapper13saveLayerCakeERKSs
```

Could you please give me some suggestions? Thanks a lot!

My CUDA version is 11.7.

**Comment by balakumar-s** [comment]
Can you use the docker provided here: https://github.com/NVlabs/curobo/blob/7196be75f5294f0997a2b55ed9f24a088d57b33e/docker/x86.dockerfile#L106

**Comment by zhanghua7099** [comment]
Thanks for your help! Using the docker environment will avoid this problem.

**Comment by balasubramani0395** [comment]
@balakumar-s 
Hi,
I face the same issue when trying to run examples. I have installed curobo, nvblox, nvblox_torch successfully with isaac_sim omni_python. 

Can I modify the python to omni_python in dockerfile and use local isaac_sim installation to build and run with the docker you suggested?

Is there any other way to fix this issue?

Thanks
